version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: rbac_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: rbac_app
      MYSQL_USER: rbac_user
      MYSQL_PASSWORD: rbac_password123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: rbac_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: rbac_user
      PMA_PASSWORD: rbac_password123
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
